services:
  fcp-fd-messages:
    build:
      context: .
      target: production
    image: fcp-fd-messages
    container_name: fcp-fd-messages
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-messages-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
